name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: |
          set -e
          npx playwright test

      - name: Always upload Playwright report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - name: Get Playwright report URL
        if: always()
        id: get-report-url
        run: echo "REPORT_URL=${{ steps.upload-playwright-report.outputs.download-url }}" >> $GITHUB_ENV

      - name: Notify Microsoft Teams
        if: always()
        run: |
          WEBHOOK_URL=${{ secrets.TEAMS_WEBHOOK_URL }}
          STATUS="Playwright tests have completed. See the report."
          REPORT_URL=${{ env.REPORT_URL }}
          PAYLOAD=$(jq -n --arg status "$STATUS" --arg report_url "$REPORT_URL" '{text: "\($status)\nReport: \($report_url)"}')
          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL"
