name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: |
          set -e
          npx playwright test

      - name: Always upload Playwright report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: playwright-report
          path: playwright-report

      - name: Set Artifact URL
        if: always()
        id: set-artifact-url
        run: echo "ARTIFACT_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts" >> $GITHUB_ENV

      - name: Notify Microsoft Teams
        if: always()
        run: |
          WEBHOOK_URL=${{ secrets.TEAMS_WEBHOOK_URL }}
          STATUS="Playwright tests have completed. See the report."
          ARTIFACT_URL=${{ env.ARTIFACT_URL }}
          PAYLOAD=$(jq -n --arg status "$STATUS" --arg artifact_url "$ARTIFACT_URL" '{text: "\($status)\nArtifact URL: \($artifact_url)"}')
          curl -H "Content-Type: application/json" -d "$PAYLOAD" "$WEBHOOK_URL"
